### ISSUE TITLE
Develop code commit process and branch management method

### ISSUE THREAD

**Issue by qtrandev** [CodeforSouth/LeafletTransit#20]
Branch management:
1) Remove HEAD branch
2) Do we want to create a DEV branch or commit into master?
3) How often do we update gh-pages branch? On every commit to master?

Code commit:
1) Should everything be done with Pull Requests or can certain trusted people commit directly and the rest Pull Requests?
2) Who should be reviewing pull requests

Other:
1) Who should assign newly created issues? Probably anyone free.

**Comment by CristinaSolana** [comment]
@qtrandev have a look at https://github.com/Code-for-Miami/contributor-workflow, might be a helpful start.

**Comment by qtrandev** [comment]
Thanks Cristina! That will be followed.

**Comment by CristinaSolana** [comment]
@qtrandev I've moved the contributor workflow to: https://github.com/Code-for-Miami/getting-started/wiki/Contributor-Workflow
