### ISSUE TITLE
Why isn't http://codeformiami.org/LeafletTransit working?

### ISSUE THREAD

**Issue by ErnieAtLYD** [CodeforSouth/LeafletTransit#21]
We have the repo on the `gh-pages` branch. Hrm.

**Comment by qtrandev** [comment]
Same thing happening with http://codeforftl.github.io/ftlviz and http://codeforftl.org/ftlviz 
I didn't even know how it got set up to automatically forward to that.

**Comment by ErnieAtLYD** [comment]
@CristinaSolana, I'm so bad at github domain forwarding it's not even funny. Got any ideas on this one?

**Comment by CristinaSolana** [comment]
@ErnieAtLYD @qtrandev Y'all got it right. I'll bet this is a DNS cache issue on GitHub side. It happens all the time. I will put in a ticket with them.

**Comment by ErnieAtLYD** [comment]
:+1:

**Comment by qtrandev** [comment]
Try doing a pull request to update gh-pages to the latest code. I did that for http://codeforftl.github.io/ftlviz and it seems to work now.

**Comment by qtrandev** [comment]
I did that and it's working now. Closing this item.

**Comment by qtrandev** [comment]
@ErnieAtLYD Can you update the link back to http://codeformiami.org/LeafletTransit ?
