### ISSUE TITLE
Register project with Code for America to use 'help wanted' tag

### ISSUE THREAD

**Issue by qtrandev** [CodeforSouth/LeafletTransit#22]
Follow instructions here to somehow register the project https://github.com/codeforamerica/civic-issue-finder#civic-issue-finder

Any issue tagged with 'help wanted' (ex: #19)should appear here:
https://www.codeforamerica.org/geeks/civicissues

**Comment by ErnieAtLYD** [comment]
Yep! We're totally registered. To have specific issues tagged from outside Code for Miami, make sure it has a `help wanted` label attached to the issue.

See: https://www.codeforamerica.org/geeks/civicissues/widget?organization_name=Code-for-Miami&labels=help%20wanted&number=12

**Comment by qtrandev** [comment]
@ErnieAtLYD I'm not seeing our issues listed when I go to https://www.codeforamerica.org/geeks/civicissues May we need to register this specific LeafletTransit somewhere else?

**Comment by ErnieAtLYD** [comment]
![img_0211](https://cloud.githubusercontent.com/assets/33945/9029198/fe05af8e-395c-11e5-85e1-568ccd5bb7e8.PNG)

Screenshot from my phone (it was sitting in my phones outbox due to a phone config issue)
