### ISSUE TITLE
Make mobile menu disappear when tapping outside menu

### ISSUE THREAD

**Issue by qtrandev** [CodeforSouth/LeafletTransit#37]
Once the menu opens on mobile, tapping outside it should make it hide again. Currently, the menu button needs to be tapped again to hide it.

**Comment by qtrandev** [comment]
@bruncun I see a commit for this but I'm not seeing a fix. The menu displays when the page first loads and clicking outside it doesn't hide it. Temporary test location: http://qtrandev.com/transit/test2/

**Comment by bruncun** [comment]
#41 is now good to go.

**Comment by qtrandev** [comment]
We fixed selecting the nav item and making the menu disappear with 5ce26a54975ab89676dcb54409ff8c76de7d8541
Can we hide the menu when the user taps outside the menu on mobile? It might be hard with the map since the map intercepts touch/click events.
