### ISSUE TITLE
Cannot scroll to bottom of page

### ISSUE THREAD

**Issue by qtrandev** [CodeforSouth/LeafletTransit#38]
We have problems with scrolling such as on the Bus Routes tab. There should be about 100 routes shown.

**Comment by qtrandev** [comment]
Fixed with 1bb2f7cca66f1e3268512414b4cf79a70f221d9b
CSS was updated.

**Comment by bruncun** [comment]
Hm, I originally disabled overflow to hide the scroll bar on the map pane to get the full screen effect. I'm going to move this to a selector and only apply it to the tabs that contain tables.

**Comment by bruncun** [comment]
#41
